"""HiCache modeling stage 的 workflow runner config 写出工具。"""

from __future__ import annotations

from pathlib import Path

from ....common.io import write_json
from ...matrix.runs.types import ProfileRun, safe_slug


def write_runner_config_for_target(target: ProfileRun, config_dir: Path) -> Path:
    """写出供 ``scripts/model.sh --config`` 消费的 Python runner config。"""

    path = runner_config_path(config_dir, target.config_id)
    payload = {
        "metadata": {
            "purpose": (
                "Generated by scripts/internal/entrypoints/hicache_workflow.py "
                "as a workflow runner config for matrix final-state prediction."
            ),
            "target_config_id": target.config_id,
            "target_run_id": target.run_id,
            "target_config_path": str(target.config_path),
            "config_kind": "workflow_runner_config",
            "backend_config_note": (
                "Per-prediction cpp_model_config.json is generated later for the C++ TraceGraph backend."
            ),
        },
        "input": {},
        "output_dir": "data/modeling_runs/hicache_state_workflow/generated",
        "mode": "cache_state",
        "cpp_trace_graph": {
            "backend_kind": "validation",
        },
        "validation": {
            "hicache_state": {
                "enabled": True,
                "require_oracle_state_trace": True,
                "oracle_page_key_mode": "strip_scope",
                "oracle_trace_paths": [],
            }
        },
        "modules": [
            {
                "name": "HiCacheModule",
                "enabled": True,
                "config": {
                    "hicache": target.hicache_config,
                },
            }
        ],
        "outputs": {
            "emit_dag_chrome_trace": False,
            "emit_module_summary": True,
            "emit_validation": True,
        },
    }
    write_json(path, payload)
    return path


def write_runner_configs_for_targets(targets: list[ProfileRun], config_dir: Path) -> dict[str, Path]:
    """按 target config id 去重写出可复用的 runner config。"""

    selected: dict[str, ProfileRun] = {}
    for target in sorted(targets, key=lambda item: (item.config_id, item.run_id)):
        selected.setdefault(target.config_id, target)
    return {config_id: write_runner_config_for_target(target, config_dir) for config_id, target in selected.items()}


def runner_config_path(config_dir: Path, target_config_id: str) -> Path:
    """返回某个 target config id 对应的 workflow runner config 路径。"""

    return config_dir / f"target_{safe_slug(target_config_id)}.json"
