"""把 workflow 输出需求转换成当前 C++ runner 配置。"""

from __future__ import annotations

from pathlib import Path
from dataclasses import dataclass
from typing import Any

from ...common.io import write_json
from ...common.paths import ROOT_DIR
from ..types import ModelRunSpec, ModelOutputRequirement, ProfileRunRef


@dataclass(frozen=True)
class RunnerConfigBuilder:
    """为一个 ModelRunSpec 生成 runner config 和执行命令。"""

    spec: ModelRunSpec

    def write_config(self, path: Path) -> Path:
        """写出底层 modeling runner 消费的 JSON。"""

        write_json(path, self.payload())
        return path

    def payload(self) -> dict[str, Any]:
        """构造 runner config payload。"""

        outputs = self._outputs_for_requirements()
        payload: dict[str, Any] = {
            "metadata": {
                "purpose": "Generated by scripts/internal/entrypoints/modeling_workflow.py.",
                "config_kind": "unified_modeling_workflow_runner_config",
                "model_run_id": self.spec.run_id,
                "mode": self.spec.mode,
                "source_run_id": self.spec.source_profile.run_id,
                "source_config_id": self.spec.source_profile.config_id,
                "target_run_id": self.spec.target_profile.run_id if self.spec.target_profile is not None else None,
                "target_config_id": self.spec.target_profile.config_id
                if self.spec.target_profile is not None
                else None,
                "validation_requests": list(self.spec.validation_requests),
                "output_requirements": sorted(requirement.value for requirement in self.spec.output_requirements),
            },
            "input": {},
            "output_dir": str(self.spec.output_dir),
            "mode": self.spec.mode,
            "cpp_trace_graph": {
                "backend_kind": "validation" if self._requires_validation_backend() else "release",
                "threads": self.spec.trace_threads,
                "file_threads": self.spec.trace_file_threads,
                "trace_channels": list(self.spec.trace_channels),
            },
            "outputs": outputs,
        }
        if self.spec.mode in {"cache_state", "cache_patch"}:
            target = require_target_profile(self.spec)
            payload.update(
                hicache_module_payload(
                    self.spec.source_profile,
                    target,
                    outputs,
                    enable_dag_patch=self.spec.mode == "cache_patch",
                )
            )
        return payload

    def command(self, runner_config_path: Path) -> list[str]:
        """构造当前底层建模执行命令。"""

        command = self._runner_entrypoint() + [
            "--config",
            str(runner_config_path),
            "--profile-manifest",
            str(self.spec.source_profile.manifest_path),
            "--output-dir",
            str(self.spec.output_dir),
            "--mode",
            self.spec.mode,
        ]
        if self.spec.mode == "cache_state":
            target = require_target_profile(self.spec)
            for oracle_path in target.python_probe_files:
                command.extend(["--hicache-oracle-trace", str(oracle_path)])
        return command

    def _runner_entrypoint(self) -> list[str]:
        """返回宿主侧单次 modeling runner 入口。"""

        return [str(ROOT_DIR / "scripts/model.sh")]

    def _outputs_for_requirements(self) -> dict[str, bool]:
        requirements = self.spec.output_requirements
        emit_validation = ModelOutputRequirement.MODULE_VALIDATION in requirements
        emit_module_summary = (
            ModelOutputRequirement.MODULE_SUMMARY in requirements
            or ModelOutputRequirement.MODULE_TRANSITION_DIAGNOSTICS in requirements
            or emit_validation
        )
        return {
            "emit_dag_chrome_trace": ModelOutputRequirement.CHROME_TRACE in requirements,
            "emit_module_summary": emit_module_summary,
            "emit_validation": emit_validation,
            "emit_dag_analysis": ModelOutputRequirement.BASE_DAG_DIAGNOSTICS in requirements,
        }

    def _requires_validation_backend(self) -> bool:
        return any(
            requirement
            in {
                ModelOutputRequirement.BASE_DAG_DIAGNOSTICS,
                ModelOutputRequirement.MODULE_VALIDATION,
                ModelOutputRequirement.MODULE_SUMMARY,
                ModelOutputRequirement.MODULE_TRANSITION_DIAGNOSTICS,
            }
            for requirement in self.spec.output_requirements
        )


def require_target_profile(spec: ModelRunSpec) -> ProfileRunRef:
    """返回 HiCache target-config 运行必须具备的 target profile。"""

    if spec.target_profile is None:
        raise ValueError(f"{spec.mode} model run requires target profile: {spec.run_id}")
    if spec.target_profile.hicache_config is None:
        raise ValueError(f"target profile has no HiCache config: {spec.target_profile.label}")
    return spec.target_profile


def hicache_module_payload(
    source: ProfileRunRef,
    target: ProfileRunRef,
    outputs: dict[str, bool],
    *,
    enable_dag_patch: bool = False,
) -> dict[str, Any]:
    """构造 HiCache runner config 中的 module 部分。"""

    source_hicache_config = {**source.hicache_config} if source.hicache_config is not None else {}
    hicache_config = {**target.hicache_config, "enable_dag_patch": enable_dag_patch}
    return {
        "validation": {
            "hicache_state": {
                "enabled": bool(outputs.get("emit_validation")),
                "require_oracle_state_trace": bool(outputs.get("emit_validation")),
                "oracle_page_key_mode": "strip_scope",
                "oracle_trace_paths": [],
            }
        },
        "modules": [
            {
                "name": "HiCacheModule",
                "enabled": True,
                "config": {
                    "hicache": hicache_config,
                    "source_hicache": source_hicache_config,
                },
            }
        ],
    }
