"""Active forced-token plan, bundle, and workload-quality contracts."""

from ...common.digests import sha256_file, sha256_json
from .bundle import (
    ForcedTokenBundlePlan,
    forced_token_bundle_summary,
    load_forced_token_bundle,
    resolve_forced_token_bundle_plan,
)
from .constants import (
    FORCED_TOKEN_BUNDLE_SCHEMA,
    FORCED_TOKEN_ERROR_BUNDLE_INPUT,
    FORCED_TOKEN_ERROR_BUNDLE_MISSING,
    FORCED_TOKEN_ERROR_BUNDLE_PLAN_HASH,
    FORCED_TOKEN_ERROR_BUNDLE_PLAN_METADATA,
    FORCED_TOKEN_ERROR_BUNDLE_PLAN_MISSING,
    FORCED_TOKEN_ERROR_BUNDLE_PROVENANCE,
    FORCED_TOKEN_ERROR_BUNDLE_SCHEMA,
    FORCED_TOKEN_ERROR_CAPTURE_OVERWRITE,
    FORCED_TOKEN_ERROR_MODE_UNKNOWN,
    FORCED_TOKEN_ERROR_ORIGIN_INPUT,
    FORCED_TOKEN_ERROR_OUTPUT_MISMATCH,
    FORCED_TOKEN_ERROR_OUTPUT_UNCHECKED,
    FORCED_TOKEN_ERROR_PLAN_MISSING,
    FORCED_TOKEN_ERROR_REQUEST_COUNT,
    FORCED_TOKEN_ERROR_REQUEST_IDS,
    FORCED_TOKEN_ERROR_REQUEST_TOKENS,
    FORCED_TOKEN_ERROR_SCHEMA_UNKNOWN,
    FORCED_TOKEN_ERROR_WORKLOAD_FINGERPRINT,
    FORCED_TOKEN_ERROR_WORKLOAD_ID,
    FORCED_TOKEN_PLAN_SCHEMA,
)
from .plan import (
    ForcedTokenPlanSummary,
    forced_token_plan_summary,
    index_plan_requests_by_logical_id,
    int_list,
    load_forced_token_plan,
    non_negative_int,
    plan_request_count,
    plan_workload_fingerprint,
    plan_workload_id,
    validate_plan_contract,
)
from .quality import (
    empty_forced_token_quality,
    forced_token_quality_from_report,
    forced_token_quality_from_workload_report,
)

__all__ = [
    "FORCED_TOKEN_BUNDLE_SCHEMA",
    "FORCED_TOKEN_ERROR_BUNDLE_INPUT",
    "FORCED_TOKEN_ERROR_BUNDLE_MISSING",
    "FORCED_TOKEN_ERROR_BUNDLE_PLAN_HASH",
    "FORCED_TOKEN_ERROR_BUNDLE_PLAN_METADATA",
    "FORCED_TOKEN_ERROR_BUNDLE_PLAN_MISSING",
    "FORCED_TOKEN_ERROR_BUNDLE_PROVENANCE",
    "FORCED_TOKEN_ERROR_BUNDLE_SCHEMA",
    "FORCED_TOKEN_ERROR_CAPTURE_OVERWRITE",
    "FORCED_TOKEN_ERROR_MODE_UNKNOWN",
    "FORCED_TOKEN_ERROR_ORIGIN_INPUT",
    "FORCED_TOKEN_ERROR_OUTPUT_MISMATCH",
    "FORCED_TOKEN_ERROR_OUTPUT_UNCHECKED",
    "FORCED_TOKEN_ERROR_PLAN_MISSING",
    "FORCED_TOKEN_ERROR_REQUEST_COUNT",
    "FORCED_TOKEN_ERROR_REQUEST_IDS",
    "FORCED_TOKEN_ERROR_REQUEST_TOKENS",
    "FORCED_TOKEN_ERROR_SCHEMA_UNKNOWN",
    "FORCED_TOKEN_ERROR_WORKLOAD_FINGERPRINT",
    "FORCED_TOKEN_ERROR_WORKLOAD_ID",
    "FORCED_TOKEN_PLAN_SCHEMA",
    "ForcedTokenBundlePlan",
    "ForcedTokenPlanSummary",
    "empty_forced_token_quality",
    "forced_token_bundle_summary",
    "forced_token_plan_summary",
    "forced_token_quality_from_report",
    "forced_token_quality_from_workload_report",
    "index_plan_requests_by_logical_id",
    "int_list",
    "load_forced_token_bundle",
    "load_forced_token_plan",
    "non_negative_int",
    "plan_request_count",
    "plan_workload_fingerprint",
    "plan_workload_id",
    "resolve_forced_token_bundle_plan",
    "sha256_file",
    "sha256_json",
    "validate_plan_contract",
]
